# Data Augumentation

In [1]:
# import all that libraries needed to me 
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
from tensorflow import keras
import tensorflow as tf
import seaborn as sns
import pandas as pd
import numpy as np
import cv2
import os
import PIL
import pathlib

In [2]:
# Read DataSet

# Images data_set

# Training sample

In [3]:
df_train_image = "E:\\wns _tringe\\train_images"

In [4]:
data_path_train = pathlib.Path(df_train_image)

In [5]:
data_path_train.glob('*.jpg')

<generator object Path.glob at 0x00000221B8997560>

In [6]:
df_train_image_1 = list(data_path_train.glob('*.jpg'))
df_train_image_1

[WindowsPath('E:/wns _tringe/train_images/10.jpg'),
 WindowsPath('E:/wns _tringe/train_images/1000.jpg'),
 WindowsPath('E:/wns _tringe/train_images/1001.jpg'),
 WindowsPath('E:/wns _tringe/train_images/1002.jpg'),
 WindowsPath('E:/wns _tringe/train_images/1003.jpg'),
 WindowsPath('E:/wns _tringe/train_images/1004.jpg'),
 WindowsPath('E:/wns _tringe/train_images/1005.jpg'),
 WindowsPath('E:/wns _tringe/train_images/1006.jpg'),
 WindowsPath('E:/wns _tringe/train_images/1008.jpg'),
 WindowsPath('E:/wns _tringe/train_images/1009.jpg'),
 WindowsPath('E:/wns _tringe/train_images/101.jpg'),
 WindowsPath('E:/wns _tringe/train_images/1010.jpg'),
 WindowsPath('E:/wns _tringe/train_images/1012.jpg'),
 WindowsPath('E:/wns _tringe/train_images/1013.jpg'),
 WindowsPath('E:/wns _tringe/train_images/1014.jpg'),
 WindowsPath('E:/wns _tringe/train_images/1015.jpg'),
 WindowsPath('E:/wns _tringe/train_images/1016.jpg'),
 WindowsPath('E:/wns _tringe/train_images/1017.jpg'),
 WindowsPath('E:/wns _tringe/tr

In [7]:
len(list(data_path_train.glob('*.jpg')))

7575

In [8]:
df_train_image_1[0]

WindowsPath('E:/wns _tringe/train_images/10.jpg')

In [9]:
#PIL.Image.open(df_train_image_1[10])

In [10]:
#PIL.Image.open(df_train_image_1[67])

In [11]:
data_path_train = pathlib.Path(df_train_image)
data_path_train.glob('*.jpg')
df_train_image_1 = list(data_path_train.glob('*.jpg'))

In [12]:
df_train_image_1[0]

WindowsPath('E:/wns _tringe/train_images/10.jpg')

In [13]:
# PIL.Image.open(df_test_image_1[0])

In [14]:
df_train_img = cv2.imread(str(df_train_image_1[0]))
df_train_img.shape

(969, 1293, 3)

In [15]:
cv2.resize(df_train_img,(180,180)).shape

(180, 180, 3)

# Testing sample

In [16]:
df_test_image = "E:\\wns _tringe\\test_images"

In [17]:
data_path_test = pathlib.Path(df_test_image)

In [18]:
df_test_image_1 = list(data_path_test.glob('*.jpg'))
df_test_image_1

[WindowsPath('E:/wns _tringe/test_images/10000.jpg'),
 WindowsPath('E:/wns _tringe/test_images/10001.jpg'),
 WindowsPath('E:/wns _tringe/test_images/10002.jpg'),
 WindowsPath('E:/wns _tringe/test_images/10003.jpg'),
 WindowsPath('E:/wns _tringe/test_images/10004.jpg'),
 WindowsPath('E:/wns _tringe/test_images/10005.jpg'),
 WindowsPath('E:/wns _tringe/test_images/10006.jpg'),
 WindowsPath('E:/wns _tringe/test_images/10007.jpg'),
 WindowsPath('E:/wns _tringe/test_images/10008.jpg'),
 WindowsPath('E:/wns _tringe/test_images/10009.jpg'),
 WindowsPath('E:/wns _tringe/test_images/10010.jpg'),
 WindowsPath('E:/wns _tringe/test_images/10011.jpg'),
 WindowsPath('E:/wns _tringe/test_images/10012.jpg'),
 WindowsPath('E:/wns _tringe/test_images/10013.jpg'),
 WindowsPath('E:/wns _tringe/test_images/10014.jpg'),
 WindowsPath('E:/wns _tringe/test_images/10015.jpg'),
 WindowsPath('E:/wns _tringe/test_images/10016.jpg'),
 WindowsPath('E:/wns _tringe/test_images/10017.jpg'),
 WindowsPath('E:/wns _tringe

In [19]:
len(df_test_image_1)

3462

In [20]:
df_test_img = cv2.imread(str(df_test_image_1[0]))
df_test_img.shape

(633, 845, 3)

In [21]:
cv2.resize(df_test_img,(180,180)).shape

(180, 180, 3)

# Function

In [22]:
# function for all training and testing data are readed and resized it

In [23]:
X = []
for i in df_train_image_1:
    train_img = cv2.imread(str(i))
    resize_train = cv2.resize(train_img,(180,180))
    X.append(resize_train)

In [24]:
X[234].shape

(180, 180, 3)

In [25]:
y = []
for i in df_test_image_1:
    test_img = cv2.imread(str(i))
    resize_test = cv2.resize(test_img,(180,180))
    y.append(resize_test)

In [26]:
y[457].shape

(180, 180, 3)

# Scaling

In [27]:
type(X)

list

In [28]:
type(y)

list

In [29]:
X = np.array(X)
X_train_img = X/255

In [30]:
y = np.array(y)
y_test_img = y/255

In [31]:
X_train_img

array([[[[0.07843137, 0.05882353, 0.05490196],
         [0.11764706, 0.09411765, 0.09019608],
         [0.1254902 , 0.10588235, 0.09411765],
         ...,
         [0.37647059, 0.37647059, 0.37647059],
         [0.34901961, 0.34901961, 0.34901961],
         [0.32156863, 0.32156863, 0.32156863]],

        [[0.10588235, 0.08627451, 0.08235294],
         [0.10588235, 0.08627451, 0.08235294],
         [0.12941176, 0.10980392, 0.09803922],
         ...,
         [0.34509804, 0.34509804, 0.34509804],
         [0.3372549 , 0.3372549 , 0.3372549 ],
         [0.34117647, 0.34117647, 0.34117647]],

        [[0.09803922, 0.07843137, 0.0745098 ],
         [0.09019608, 0.07058824, 0.06666667],
         [0.09411765, 0.0745098 , 0.0627451 ],
         ...,
         [0.35294118, 0.35294118, 0.35294118],
         [0.34509804, 0.34509804, 0.34509804],
         [0.34901961, 0.34901961, 0.34901961]],

        ...,

        [[0.06666667, 0.05098039, 0.04705882],
         [0.07843137, 0.0627451 , 0.05882353]

In [32]:
y_test_img 

array([[[[0.83921569, 0.83529412, 0.74509804],
         [0.94901961, 0.94509804, 0.86666667],
         [0.87843137, 0.87058824, 0.78039216],
         ...,
         [0.49803922, 0.55686275, 0.5372549 ],
         [0.54117647, 0.53333333, 0.38039216],
         [0.84705882, 0.79215686, 0.82352941]],

        [[0.84313725, 0.80392157, 0.68235294],
         [0.83137255, 0.79215686, 0.67058824],
         [0.69019608, 0.65098039, 0.5254902 ],
         ...,
         [0.47843137, 0.54901961, 0.54117647],
         [0.25490196, 0.24705882, 0.1254902 ],
         [0.83529412, 0.77647059, 0.74901961]],

        [[0.18431373, 0.17254902, 0.10588235],
         [0.14509804, 0.13333333, 0.05490196],
         [0.24705882, 0.23529412, 0.15686275],
         ...,
         [0.56862745, 0.6745098 , 0.69803922],
         [0.16862745, 0.18823529, 0.11764706],
         [0.65490196, 0.61176471, 0.51372549]],

        ...,

        [[0.63137255, 0.66666667, 0.67058824],
         [0.64705882, 0.67843137, 0.68235294]

In [33]:
y_test_img = y_test_img/255
y_test_img

array([[[[3.29104191e-03, 3.27566321e-03, 2.92195309e-03],
         [3.72164552e-03, 3.70626682e-03, 3.39869281e-03],
         [3.44482891e-03, 3.41407151e-03, 3.06036140e-03],
         ...,
         [1.95309496e-03, 2.18377547e-03, 2.10688197e-03],
         [2.12226067e-03, 2.09150327e-03, 1.49173395e-03],
         [3.32179931e-03, 3.10649750e-03, 3.22952710e-03]],

        [[3.30642061e-03, 3.15263360e-03, 2.67589389e-03],
         [3.26028451e-03, 3.10649750e-03, 2.62975779e-03],
         [2.70665129e-03, 2.55286428e-03, 2.06074587e-03],
         ...,
         [1.87620146e-03, 2.15301807e-03, 2.12226067e-03],
         [9.99615532e-04, 9.68858131e-04, 4.92118416e-04],
         [3.27566321e-03, 3.04498270e-03, 2.93733180e-03]],

        [[7.22798923e-04, 6.76662822e-04, 4.15224913e-04],
         [5.69011918e-04, 5.22875817e-04, 2.15301807e-04],
         [9.68858131e-04, 9.22722030e-04, 6.15148020e-04],
         ...,
         [2.22991157e-03, 2.64513649e-03, 2.73740869e-03],
         [

In [34]:
# X_train_img[3]

In [35]:
df_train = pd.read_csv("E:\\wns _tringe\\train.csv")
df_train = df_train[:7575]
df_train.head()

image_id filename  label
0         1    1.jpg      0
1         2    2.jpg      0
2         3    3.jpg      0
3         4    4.jpg      0
4         5    5.jpg      0

In [36]:
df_train.shape

(7575, 3)

In [37]:
df_test = pd.read_csv("E:\\wns _tringe\\test.csv")
df_test = df_test[:3462]
df_test.head()

image_id  filename
0      8080  8080.jpg
1      8081  8081.jpg
2      8082  8082.jpg
3      8083  8083.jpg
4      8084  8084.jpg

In [38]:
# 0 - non fraudulent claim 
# 1 - fraudulent claim

In [39]:
df_train["filename"] = df_train["filename"].apply(lambda x: int(x.split(".")[0]))
df_train.head()

image_id  filename  label
0         1         1      0
1         2         2      0
2         3         3      0
3         4         4      0
4         5         5      0

In [40]:
df_train.shape

(7575, 3)

In [41]:
df_train.isnull().sum()

image_id    0
filename    0
label       0
dtype: int64

In [42]:
df_test["filename"] = df_test["filename"].apply(lambda x: int(x.split(".")[0]))
df_test.head()

image_id  filename
0      8080      8080
1      8081      8081
2      8082      8082
3      8083      8083
4      8084      8084

In [43]:
df_test.shape

(3462, 2)

In [44]:
X_train_csv = df_train.drop('label',axis=1)
y_train_csv = df_train[['label']]

In [45]:
X_train_csv.shape

(7575, 2)

In [46]:
y_train_csv.shape

(7575, 1)

In [47]:
X_train_csv.head()

image_id  filename
0         1         1
1         2         2
2         3         3
3         4         4
4         5         5

In [48]:
y_train_csv.head()

label
0      0
1      0
2      0
3      0
4      0

In [49]:
X_test_csv = df_test
X_test_csv.head()

image_id  filename
0      8080      8080
1      8081      8081
2      8082      8082
3      8083      8083
4      8084      8084

In [50]:
X_test_csv.shape

(3462, 2)

In [51]:
X_test_csv.isnull().sum()

image_id    0
filename    0
dtype: int64

In [52]:
n = 3462
class ReplaceValues:
    def __init__(self, X_test_csv):
        self.X_test_csv = X_test_csv
    def replace_values_1(self):
        for i, value in enumerate(self.X_test_csv['image_id']):
            if value >= 8080:
                self.X_test_csv.at[i, 'image_id'] = i % n 
    def replace_values_2(self):
        for i, value in enumerate(self.X_test_csv['filename']):
            if value >= 8080:
                self.X_test_csv.at[i, 'filename'] = i % n

In [53]:
replacer = ReplaceValues(X_test_csv)
replacer.replace_values_1() 
replacer.replace_values_2() 

In [54]:
X_test_csv.head()

image_id  filename
0         0         0
1         1         1
2         2         2
3         3         3
4         4         4

In [55]:
data_augumentation = keras.layers.experimental.preprocessing.RandomZoom(0.5)

In [56]:
data_augumentation = keras.Sequential([
    keras.layers.experimental.preprocessing.RandomZoom(0.5),
])

# some steps hide for only a reason of memory location error

In [57]:
# plt.axis("off")
# plt.imshow(X[0])
# plt.show()

In [58]:
# image = data_augumentation(X)[0].numpy().astype('uint8')

# plt.axis('off')
# plt.imshow(image)
# plt.show()

In [59]:
# data_augumentation = keras.layers.experimental.preprocessing.RandomContrast(0.5)
# plt.axis('off')
# plt.imshow(data_augumentation(X)[0].numpy().astype('uint8'))
# plt.show()

In [60]:
# data_augumentation = keras.layers.experimental.preprocessing.RandomFlip('horizontal')
# plt.axis('off')
# plt.imshow(data_augumentation(X)[0].numpy().astype('uint8'))
# plt.show()

In [61]:
data_augumentation = keras.Sequential([
    keras.layers.experimental.preprocessing.RandomFlip('horizontal',input_shape=(180,180,3)),
    keras.layers.experimental.preprocessing.RandomRotation(0.1),
    keras.layers.experimental.preprocessing.RandomZoom(0.1)
])

In [62]:
data_augumentation_model = keras.Sequential([
    data_augumentation,
    keras.layers.Conv2D(16,3,padding='same',activation='relu'),
    keras.layers.MaxPooling2D(),
    keras.layers.Conv2D(32,3,padding='same',activation='relu'),
    keras.layers.MaxPooling2D(),
    keras.layers.Conv2D(64,3,padding='same',activation='relu'),
    keras.layers.MaxPooling2D(),
    keras.layers.Flatten(),
    keras.layers.Dense(128,activation='relu'),
    keras.layers.Dense(10,activation='relu'),
    keras.layers.Dense(5,activation='sigmoid')
])

In [63]:
data_augumentation_model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['Accuracy'])

In [64]:
data_augumentation_model.fit(X_train_img,y_train_csv,epochs=2)

Epoch 1/2


237/237 [==============================] - 40s 155ms/step - loss: 0.2516 - Accuracy: 0.9391
Epoch 2/2
237/237 [==============================] - 36s 153ms/step - loss: 0.2233 - Accuracy: 0.9430


In [65]:
y_test_img = y_test_img.astype(np.float32)

In [1]:
# hide because get memory location error 
# data_augumentation_model.evaluate([X_train_img,X_test_csv],y_test_img,batch_size=8)

In [2]:
# # using gradient accumulation also try to find evaluation of but it can give also same error so i can hide here mutiple steps
# # Define hyperparameters
# accumulation_steps = 4 # Number of batches to accumulate gradients over

# # Create optimizer and define gradient accumulation logic
# optimizer = tf.keras.optimizers.Adam()
# accumulator = tf.keras.metrics.Mean()

# # Convert arrays or tensors to TensorFlow Dataset
# train_dataset = tf.data.Dataset.from_tensor_slices((X_train_img, y_train_csv)).batch(32)

# # Training loop
# for epoch in range(2):
#     for step, (x_batch, y_batch) in enumerate(train_dataset):
#         with tf.GradientTape() as tape:
#             predictions = model(x_batch)
#             loss = loss_function(y_batch, predictions)

#         # Accumulate gradients
#         gradients = tape.gradient(loss, model.trainable_variables)
#         accumulator.update_state(loss)

#         # Update model weights after accumulation steps
#         if (step + 1) % accumulation_steps == 0:
#             optimizer.apply_gradients(zip(gradients, model.trainable_variables))
#             accumulator.reset_states()